### ISSUE TITLE
Allow ILaunchPluginServices to process class bytes if they prefer

### ISSUE THREAD

**Issue by Runemoro** [cpw/modlauncher#10]
Although most launch plugins will be using ASM to transform classes, launch plugins should still have the option of directly parsing class bytes, for several reasons:
 - For efficiency, rather than working with a ClassNode, a launch plugin could create a custom class visitor which doesn't read the whole class, for example by returning a `MethodWriter` as their method visitor, in which case ASM will give the bytes directly to the MethodWriter (see lines 1123-1139 of ClassReader.java)
 - A launch plugin may want to use something other than ASM to transform their class, just load a cached transformed class from a file, or replace the class with `null` (in the case of a SideOnly transformer)
 - A launch plugin may want to just save the class to a file, for debugging, without actually transforming it

I suggest adding methods `byte[] processClassBytes(ClassNode classNode, final Type classType)` and `boolean handlesClassBytes(Type classType, final boolean isEmpty)` to the ILaunchPluginService interface. 

This way, a ClassNode would only be created if there is a plugin that wants to process the ClassNode, and not just plugins that process the class bytes. Plugins handling class bytes should run either before or after all plugins handling class nodes.

**Comment by cpw** [comment]
No. It is inefficient, and a significant cost.

**Comment by Runemoro** [comment]
Just to be clear, I'm not suggesting to *replace* handling ClassNodes with handling byte[]s. I'm just suggesting to offer the possibility for a plugin that doesn't need the ClassNode to process the class bytes without the overhead of creating a ClassNode. 

For example:
 - An access transformer doesn't need to read the instruction in the methods, it can just return a `MethodWriter` as its method visitor and ASM will skip that step
 - A transformer may cache its results, and return the cached class if it is available
 - A SideOnly transformer may want to throw an exception if a class is loaded, based on only the class's name, and not all of its contents. A SideOnly transformer may also want to copy over methods without having ASM parse the methods' bytecode.
