### ISSUE TITLE
Anything not in the inital classpath cannot provide a ITransformationService

### ISSUE THREAD

**Issue by ichttt** [cpw/modlauncher#22]
[The ITransformationService map ](https://github.com/cpw/modlauncher/blob/745b6f9a12a682bce3afec2aeaa530ad93a7cde8/src/main/java/cpw/mods/modlauncher/TransformationServicesHandler.java#L24)is populated very early in the cycle, so only anything that is not on the launch class path wil lnot be scanned for ITransformationServices.
This mean 3rd party class transformation providers (like Mixin, Optifine, etc) have no access to ILaunchPluginService (which is intended IIRC) AND no access to ITransformationService (which they should have IMO, as it has a much ITransformers are much more locked down)

**Comment by cpw** [comment]
Note that mixin should _not_ be loading as an ITransformationService, it should be loading, via the classpath, as an ILaunchPluginService. However, the point stands. Transformers need to be able to offer additional transformers to the system, for subsequent loading.

**Comment by cpw** [comment]
The newest release allows plugging in an "early discovery service" to facilitate this. However, it's still not what Mixin should be using.
