### ISSUE TITLE
FileNotFoundException on first launch

### ISSUE THREAD

**Issue by JoJoDeveloping** [cpw/modlauncher#30]
See https://github.com/cpw/modlauncher/commit/943824910f1320b6e131701835fe6471b4ef73dd#r33902825
Searching for additional locators on first launch fails since this is so early that the mods dir is not yet there because proper Forge has not done any initialisation.
A fix would be to either ignore the folder if missing, or to create it. IDK which is better so I haven't PR'd this yet.

**Comment by cpw** [comment]
Not a bug in ModLauncher, but in Forge, since forge provides the locator.
