### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by FrostDelta123** [cpw/modlauncher#34]
log https://gist.github.com/FrostDelta123/1c81b1ea4833cf9876b1488b45190b05

Client-args

`	"--launchTarget",
	"fmlclient",
	"--fml.forgeVersion",
	"28.0.49",
	"--fml.mcVersion",
	"1.14.4",
	"--fml.forgeGroup",
	"net.minecraftforge",
	"--fml.mcpVersion",
	"20190719.225934"`

**Comment by DaemonUmbra** [comment]
What's Gravit Launcher?

**Comment by FrostDelta123** [comment]
> What's Gravit Launcher?

Launcher for mod-projects by Russian devs

**Comment by Unnoen** [comment]
Anything other than the Vanilla launcher is not supported.

**Comment by FrostDelta123** [comment]
But what’s the different? It can’t be fixed by universal patch?

**Comment by Unnoen** [comment]
Forge is designed to work with the vanilla ecosystem, if another launcher doesn't work, it's on them to fix it. Try to replicate the error in the vanilla launcher.

**Comment by FinnT730** [comment]
Cracked launcher I think...
