### ISSUE TITLE
Obtaining class bytecode

### ISSUE THREAD

**Issue by Mumfrey** [cpw/modlauncher#36]
This issue follows on from #35 and getting rid of hacky things in the [`Internals`](https://github.com/SpongePowered/Mixin/blob/0.8/src/modlauncher/java/org/spongepowered/asm/service/modlauncher/Internals.java) class which works around the limitations using reflection for the time being.

### Background

Mixin obtains `ClassNode`s for three purposes:

* Obtaining mixin classes ready for pre-processing and application
* Obtaining class metadata to conform and validate mixins prior to application, and populate class metadata ([see note of `ClassInfo` here](https://github.com/SpongePowered/Mixin/wiki/Flippin'-Mixins,-how-do-they-work%3F#3221-parsing-mixins))
* Obtaining mixin inner class data to synthesize target-conformed inner classes for mixins as they are applied (eg. `WorldMixin$1` being resynthesized to `World$MixinInner$1`)

In general the `ClassNode` needs to pass through the transformer chain. Under LaunchWrapper the approach was to create a *delegation list* of transformers which were *not* re-entrant and simply apply them manually.

### The current hack

The current horrendous, reflection-based hack to achieve this is executed as follows:

* The [ModLauncherBytecodeProvider](https://github.com/SpongePowered/Mixin/blob/0.8/src/modlauncher/java/org/spongepowered/asm/service/modlauncher/ModLauncherBytecodeProvider.java) is registered as an *interceptor* which is a delegate of the launch plugin.
* When a `ClassNode` is requested, the bytecode provider stuffs an entry into a `Map` for the name of the class. The provider then [*simulates the class load*](https://github.com/SpongePowered/Mixin/blob/0.8/src/modlauncher/java/org/spongepowered/asm/service/modlauncher/Internals.java#L173) using a mixture of logic stolen from the delegating class loader, and reflection into the class transformer.
* Since launch plugins can process classes passing through the chain, the interceptor can detect and retain the `ClassNode` it's looking for.
* Depending on the state of the `runTransformers` flag, the interceptor throws an exception either `BEFORE` or `AFTER` transformation, including the captured `ClassNode` as an argument
* The interceptor catches the exception and receives and returns the `ClassNode`

This is obviously pretty horrible, but it's the only sensible way I could think of to faithfully replicate the class loading process to both run the transformers and retain the working `ClassNode` without replicating all the ML logic externally.

### Possible Solutions

I'm throwing myself on the mercy of the court here, because I know this is some kind of crime against humanity. Some possible solutions might be:

* **Provide this action as a service** - currently the Mixin subsystem is engineered in such a way that obtaining bytecode is the sole responsibility of the [`IClassBytecodeProvider`](https://github.com/SpongePowered/Mixin/blob/0.8/src/main/java/org/spongepowered/asm/service/IClassBytecodeProvider.java) service interface. If this functionality could be internalised to ML then the hacky service can go away and simply delegate to the official one.

* **Allow launch plugins to do more** - obviously a drawback with a service is that other transformers might abuse this power. One solution might be to only expose this capability to launch plugins (either have them receive delegates which can execute specialised actions, or the `ClassTransformer` itself?

* **Formalise the class metadata service into escrow** - another solution might be to formalise what [`ClassInfo`](https://github.com/SpongePowered/Mixin/blob/0.8/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java) is doing into a pluggable ML service, which itself has the power to obtain the bytecode. This would be nice to have, but the drawback is the complexity of specifying such a service in a reasonable timescale.

I'm sure there are other ways but these are just some initial thoughts.

**Comment by cpw** [comment]
I don't understand your ask here.

**Comment by Mumfrey** [comment]
Looking through the other issues here, this is basically a corollary (or possibly duplicate) of #4, though with a slightly narrower scope.

It actually boils down to two actualy where Mixin needs to obtain bytecode for a class without actually classloading it, but does need that bytecode to be transformed "normally" by everything except itself. (Using bytecode/classnode interchangably here since the format doesn't matter to me). The two cases are:

1. Obtaining classnode for a "template" class. This is a class which *shouldn't* be classloaded, it is used as a template for other things. This includes actual mixin bytecode to be loaded, parsed, and applied to targets as well as inner classes of those mixins which need to be synthesized into new versions for the target classes to use. For example if a mixin has an inner class `MyMixin$MyInnerClass` that "class" must not be loaded, it will be loaded as `MixinTarget$RepatriatedInnerClass` or `OtherMixinTarget$RepatriatedInnerClass` and never as its original self. This means the original code passes through the transformer chain once, like it would under a normal class load operation but it never makes it as far as the ClassLoader.

2. Obtaining classnode for an arbitrary class to generate metadata for it. This is because the pipeline is such that a bunch of things in the class hierarchy need to be known before a mixin is applied, but if we wait until class load to obtain those data then it's too late to do anything with them. This includes enumerating fields, methods and interfaces on target classes. Since additional fields, methods and interfaces might be added by transformers - or of course removed - this bytecode needs to travel through the transformer chain as well. This doesn't happen for *every* class, only classes referenced by mixins.

The ask here is that there isn't an elegant way to obtain the bytecode and run the transformer chain on it without the kind of ugly hacks that I've wrapped in `Internals` which

* Obtain the original bytecode in a mundane way
* Pass it through the transformer chain with simple reflection
* Short-circuit the transformer chain by throwing an exception

Which works but is somewhat inelegant.

The duties in question are handled by [`IClassBytecodeProvider`](https://github.com/SpongePowered/Mixin/blob/0.8/src/main/java/org/spongepowered/asm/service/IClassBytecodeProvider.java) so you can see the duties required here.

Hopefully that makes more sense? I'll be around this evening anyway if you want to discuss it some more.
