### ISSUE TITLE
Whole-class transformers run after (and overwrite) method & field transformers

### ISSUE THREAD

**Issue by Cadiboo** [cpw/modlauncher#37]
This is more an issue with OptiFine but I don't see how OptiFine can fix it without changes to ModLauncher.

Currently class transformers run after method transformers, so OptiFine's class transformations overwrite my method transformations. Without transformer ordering (#32) there is no way to make sure that my transformer runs before OptiFine's.

I think that class transformers should run before field & method transformers as they are more likely to be doing large scale transformations. Field & method transformers are more likely to be used for smaller & more directed injections.

This is directly related to [NoCubes/issues/61](https://github.com/Cadiboo/NoCubes/issues/61)
<img width="931" alt="Screen Shot 2019-09-24 at 9 29 21 pm" src="https://user-images.githubusercontent.com/37298044/66283928-31c1a180-e911-11e9-9e5c-687522da5822.png">

**Comment by Barteks2x** [comment]
As it is I don't think even adding the capabilities of the voting system to js coremods would solve this.

This is *almost* possible with a transformation service. But even there I'm not sure if this is the 100% correct way but from `IEnvironment` you can check if OptiFine (or other transformer) , and then a transformer can do something like this when voting:
```java
        boolean optifineRan = context.getAuditActivities().stream().anyMatch(activity -> 
            activity.getType() == ITransformerActivity.Type.TRANSFORMER && activity.getContext()[0].equals("OptiFine"));
        return optifineRan ? TransformerVoteResult.YES : TransformerVoteResult.DEFER;
```

The issue is that there is no way to know whether other service has the same class as a target in the first place. While someone could hardcode it based on what is known to be targetted, this seems like a very fragile, hard to debug when it breaks, approach.

As I understand it the intention was that coremods should be flexible enough to be able to run in any order without breaking. Unfortunately this is not the reality, and optifine probably will never be nice for other coremods there, as OptiFine is taking the original MC class and patching that, completely ignoring the actual input classnode. This doesn't seem solvable without optifine moving away from binary patches.

**Comment by cpw** [comment]
Yeah, the voting system should allow both you and optifine to know the other exist and maybe act differently accordingly, or just give up and crash.

**Comment by cpw** [comment]
I currently don't really expose that in JS because I wasn't sure how I would do so.

**Comment by cpw** [comment]
By the way, I do capture the audit of who touches any class, and I do know that optifine is in the "candidate list". This can be exposed in the vote.

**Comment by Cadiboo** [comment]
> By the way, I do capture the audit of who touches any class, and I do know that optifine is in the "candidate list". This can be exposed in the vote.

If this could be exposed to the JS system somehow, along with the ability to “vote” from JS, this would resolve my issue without changing the ordering as I would be able to change my JS method transformer to a JS class transformer and still apply my modifications after OptiFine.

**Comment by Cadiboo** [comment]
Since this issue doesn't seem like it's ever going to get resolved, here's the fix I implemented.
Class transformer runs after all field and method transformers.
I am specifically trying to run my method transformer after OptiFine's class transformer.
Because OptiFine is a transformer plugin or whatever it is the first class transformer to run.
So in my coremod javascript I just [wrap](https://github.com/Cadiboo/NoCubes/blob/98f87a88cbbc896f2614c739d8f9698f40588735/src/main/resources/nocubes-transformer.js#L62) all my method transformers with class transformers.
[Here's](https://github.com/Cadiboo/NoCubes/blob/98f87a88cbbc896f2614c739d8f9698f40588735/src/main/resources/nocubes-transformer.js#L1954-L2031) the javascript code.

**Comment by Cadiboo** [comment]
Why was this closed? This isn’t resolved, I just managed to hack around my specific scenario. Unless guarantees are made that JavaScript coremods will always be loaded after transformation services, I don’t think that this is resolved. My hack doesn’t work the other class transformer In question is also a JavaScript transformer.

I think the best fix for this would be allowing coremods to define other coremods they need to load before/after. This would require only small changes to the transformers json file schema.

**Comment by nallar** [comment]
Look at the commit cpw closed this with. ec2b00285d6e809d877862bfbd036f94cb877598

**Comment by Cadiboo** [comment]
> Look at the commit cpw closed this with. [ec2b002](https://github.com/cpw/modlauncher/commit/ec2b00285d6e809d877862bfbd036f94cb877598)

Oops, somehow didn’t see that, my bad.

**Comment by sp614x** [comment]
When the OF transformer is changed to use `Target.targetPreClass(...)` it crashes with:
```
Invalid target CLASS for transformer optifine.OptiFineTransformer@2e185cd7
java.lang.IllegalArgumentException: The transformer contains invalid targets
	at cpw.mods.modlauncher.TransformationServiceDecorator.gatherTransformers(TransformationServiceDecorator.java:97)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseServiceTransformers$6(TransformationServicesHandler.java:101)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$366/1562764987.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseServiceTransformers(TransformationServicesHandler.java:101)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:64)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

```
Probably `TransformTargetLabel` is not updated to use `PRE_CLASS` or the decorator check has to be fixed.
