### ISSUE TITLE
getResources broken

### ISSUE THREAD

**Issue by cpw** [cpw/modlauncher#39]
getResources is broken. See MinecraftForge/MinecraftForge#6029

**Comment by Zidane** [comment]
@cpw 

Any work towards this yet? Unless I am missing something, would require a spec break as the classBytesFinder will need to tell the TransformingClassLoader the URLs.

**Comment by ItsDoot** [comment]
Without this working, java ServiceLoaders do not work in classes loaded by TransformingClassLoader.

**Comment by cpw** [comment]
Will be reviewing tomorrow. Had a brain wave last night...
