### ISSUE TITLE
Getting class bytes of other classes in a transformer

### ISSUE THREAD

**Issue by nallar** [cpw/modlauncher#4]
## Why do transformers depend on bytecode of other classes?

* Finding superclasses/interfaces
* * Stackmap generation (getCommonSuperClass()) - required when adding new control flow
* * SpongePowered/Mixin - [ClassInfo](https://github.com/SpongePowered/Mixin/blob/d31ccf1220e31b875ab47a38c3d2ff6a05d961bf/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java)
* Find existing Methods and fields
* * javassist - needs symbols in other classes to compile source code against them
* * SpongePowered/Mixin - [ClassInfo](https://github.com/SpongePowered/Mixin/blob/d31ccf1220e31b875ab47a38c3d2ff6a05d961bf/src/main/java/org/spongepowered/asm/mixin/transformer/ClassInfo.java)

This list is probably incomplete.

## Current situation - dangerous and slow

Existing mods which depend on previous class bytes do this in one of three ways:

* Load the class they need info on, causing that class to be fully transformed
* * ["Reentrant transformer"](https://github.com/SpongePowered/Mixin/blob/d31ccf1220e31b875ab47a38c3d2ff6a05d961bf/src/main/java/org/spongepowered/asm/mixin/MixinEnvironment.java#L777)
* * Causes classloading order to change
* * infinite recursion if two transformers do this on classes and both depend on the class bytes of each other's class  
can't be used in general on all classes due to infinite recursion risk.  
always acceptable if used only for superclass/interface loading as calling defineClass will cause these classes to get loaded anyway
* Get class bytes from disk, run through earlier transformers again
* * Slow
* * Runs transformers multiple times
* * Changes classloading order with reentrant transformer, may fail completely
* * Depends on reflection into LaunchClassLoader
* Get class bytes from disk, run only through some hardcoded non-reentrant transformers
* * Slow
* * Wrong info - if a transformer before you which isn't one of your hardcoded transformers changes super classes/adds fields you won't know about this
* * Depends on reflection into LaunchClassLoader

### Current known reentrant/retransforming transformers

* [net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer](https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/fml/common/asm/transformers/EventSubscriptionTransformer.java) - reentrant
* [net.minecraftforge.fml.common.asm.transformers.TerminalTransformer](https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/fml/common/asm/transformers/TerminalTransformer.java) - reentrant
* [org.minimallycorrect.modpatcher.api.ModPatcherTransformer$ClassTransformer](https://github.com/MinimallyCorrect/ModPatcher/blob/288d4b08d976e803b7ebfc5765592e13cfa4538c/src/main/java/org/minimallycorrect/modpatcher/api/ModPatcherTransformer.java#L117) - retransforms using hardcoded transformer list only
* [org.spongepowered.asm.mixin.transformer.Proxy](https://github.com/SpongePowered/Mixin/blob/3e0d070a91d945da76cf00c45817592a6a98477f/src/launchwrapper/java/org/spongepowered/asm/mixin/transformer/Proxy.java) - retransforms using non-reentrant transformers only (hardcoded/additionally runtime detected)

This list is probably incomplete.

## getCurrentClassBytes(name) - simple, less broken solution

The simplest solution is that when requesting the current class bytes by name inside a transformer, we run that class through all transformers until it reaches the current transformer, then store this result, then return it.

When it later comes to time to transform this class normally, the cached partial transformation will be reused, and we won't re-run the earlier transformers.

A problem occurs when you need to access a class which has already been fully transformed or has been partially transformed further than the current transformer.
Do you run it through all the earlier transformers again? Do you give it the already fully transformed result? Do we store all intermediate transformation results?

The first option causes poor performance, the second is wrong and could cause subtle bugs (different result depending on classloading order), the third causes awful memory usage.

## Multi pass transformation before minecraft launch - big change from the current way, more correct?

An alternative would be to change transformation to run in passes and on all classes.
We would run all classes through transformer A. All classes through transformer B, and so on. The results would be stored in memory until the final class, then stored to disk as binpatches (or the final classes? Is there a copyright issue here? Don't think so as it's only on disk on the user's machine).
This process would happen only on the first launch, or when a new transformer is added (new mod with transformer), or a transformer signals that the cache should be invalidated. (Similar to #3)

Existing transformers which don't depend on classes existing already could continue to work. Transformers which are reentrant or retransforming would need updated.

**Comment by cpw** [comment]
This is a complicated issue. We're not going to frontload every possible class - that is not going to happen - it's slow and unecessary for the most part. Getting metadata about classes is definitely something that is planned for. I have ideas for a metadata service that should be able to help  with a lot of what you're discussing here.

**Comment by nallar** [comment]
Do you have a rough outline of how your metadata service would avoid loops?

**Comment by jredfox** [comment]
what if and here me out. That you always made sure super classes loaded first fully before transformer sub classes? there still might be an issue if superclasses load sub classes.

**Comment by jredfox** [comment]
This will help you guys. It's simple clean and can be adapted using ob/deob map.
https://github.com/llbit/ow2-asm/blob/master/test/conform/org/objectweb/asm/ClassWriterComputeFramesTest.java#L132
