### ISSUE TITLE
Incorrect logic for additional resource name check

### ISSUE THREAD

**Issue by Towdium** [cpw/modlauncher#40]
In document of method `additionalResourcesLocator` it says:

> Rules:
> The Strings in the set must not end with ".class". Conflicts with other ITransformationServices will result in an immediate crash.

But inside [TransformationServiceDecorator][1], it checks the name with this logic:

```java
final Set<String> badResourceNames = resNames.stream().
                    filter(s -> !s.endsWith(".class") || resourceNames.contains(s)).
                    collect(Collectors.toSet());
```

It seems inverted to me. Am I getting something wrong?

[1]: https://github.com/cpw/modlauncher/blob/master/src/main/java/cpw/mods/modlauncher/TransformationServiceDecorator.java#L144

**Comment by cpw** [comment]
Yes, I believe you are.

**Comment by ichttt** [comment]
No he is right, this check is the wrong way around, this crashes if a resource does not end with .class
