### ISSUE TITLE
Dealing with different classloaders

### ISSUE THREAD

**Issue by qlow** [cpw/modlauncher#46]
Hey!
I want to call a mod init method from the Minecraft class but apparently it loads the mod in a different classloader:
`MC: cpw.mods.modlauncher.TransformingClassLoader` 
`INIT: sun.misc.Launcher$AppClassLoader`

How am I supposed to deal with such a situation? Because in my mod's classloader context (or however you call it) I'm not able to access the Minecraft instance (it's null) so my mod becomes useless. I would really appreciate some advice on this.

Thanks in advance!

**Comment by DaemonUmbra** [comment]
Can I ask why you need to mess with classloaders?

**Comment by covers1624** [comment]
They aren't, from what I can understand, they are injecting a callback _somewhere_ in the Minecraft class calling their mod code, and their mods class is getting loaded with the wrong ClassLoader.

**Comment by DaemonUmbra** [comment]
This is smelling a bit of XY to me now, I need more context

**Comment by LexManos** [comment]
Welcome to the wonderful world that is classloading.
Do not add runtime code in the same jar as your coremod.
And use the standard [Coremod](https://github.com/MinecraftForge/CoreMods) system if you must be a coremod.

**Comment by qlow** [comment]
> Welcome to the wonderful world that is classloading.
> Do not add runtime code in the same jar as your coremod.
> And use the standard [Coremod](https://github.com/MinecraftForge/CoreMods) system if you must be a coremod.

My mod is going to work with or without Forge.

I solved it by using sp614x's approach in Optifine #31 
`public Map.Entry<Set<String>, Supplier<Function<String, Optional<URL>>>>
      additionalClassesLocator() {
    Set<String> key = Collections.singleton("....");
    Supplier<Function<String, Optional<URL>>> value = () -> this::getResourceUrl;
    return new AbstractMap.SimpleEntry<>(key, value);
  }

  public Optional<URL> getResourceUrl(String name) {
    return this.resourceProvider.getResourceUrl(name);
  }`

ResourceProvider is an interface that returns an Optional<URL> with the right location of the class.
