### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by tajemniktv** [cpw/modlauncher#47]
Hello, 
I can't start a game and the logs led me here.

Latest: https://hasteb.in/ipeyavof.md
Debug: https://hasteb.in/zogidibe.md

Greetings
TajemnikTV

**Comment by FinnT730** [comment]
This is not the right repo for this....
But, since we are here now, try it without optifine. It is likely the problem.

**Comment by tajemniktv** [comment]
Oh, the `at cpw.mods.modlauncher` misled me. 
Still the same problem without Optifine

**Comment by FinnT730** [comment]
Can you also give the log without optifine?

**Comment by tajemniktv** [comment]
Yea, sure :) 

Latest: https://hasteb.in/ifuqetil.md
Debug: https://hasteb.in/uqituhim.md

**Comment by FinnT730** [comment]
So, I should have seen this sooner....
Can you try it with Java 8? Minecraft is build for java 8, and you are using java 11

**Comment by tajemniktv** [comment]
Default Java

Latest: https://hasteb.in/toviyotu.md
Debug: https://hasteb.in/yoxefedi.md

**Comment by LXGaming** [comment]
Remove or update performant, You're currently loading a 1.12.2 version which aside from it being for a completely different Minecraft version also has Mixin compiled in which is causing class conflicts with MixinBootstrap which is why you're getting an IllegalAccessError.

**Comment by FinnT730** [comment]
Mate, this is 1.15
Look better, it is at the top of both files. I already asked in discord if something changes or not.

**Comment by tajemniktv** [comment]
Oh my... I haven't seen that I've downloaded Performant for 1.12
Thank You so much, if not You, I'd still be stuck...

**Comment by FinnT730** [comment]
Wait.... What is performant???

**Comment by tajemniktv** [comment]
https://www.curseforge.com/minecraft/mc-mods/performant

> small,lightweight mod project which hugely improves TPS and blocklag.

**Comment by LXGaming** [comment]
No problem, Make sure to close this issue if it's been solved.

Finn, If you read the end of Line 7 in the `debug.log` it shows ModLauncher loading `performant-1.12.2-1.10.jar`

**Comment by FinnT730** [comment]
Yeah... Read it wrong, thanks for noticing... But hard to fix things when you are on the ohone haha
