### ISSUE TITLE
Expose package filters to ILaunchPluginService

### ISSUE THREAD

**Issue by jamierocks** [cpw/modlauncher#48]
Currently only the `ILaunchHandlerService` is able to interact with [ITransformingClassLoader#addTargetPackageFilter(Predicate<String>)](https://github.com/cpw/modlauncher/blob/79f13f769a8102c3426e4bef47930503cb2b710f/src/main/java/cpw/mods/modlauncher/api/ITransformingClassLoader.java#L28), an omission I noticed while passing mod metadata from a IModLocator through to a `ModContainer` (using metadata other than nightconfig, which is excluded by Forge).

There seems to be other scenarios where this is required too, such as [MixinBootstrap](https://github.com/LXGaming/MixinBootstrap/blob/master/src/main/java/io/github/lxgaming/mixin/launch/MixinLaunchPluginService.java) - where they hack around the API limitation by using the Thread context class loader.
```java
public void initializeLaunch(ITransformerLoader transformerLoader, Path[] specialPaths) {
    TransformingClassLoader classLoader = (TransformingClassLoader) Thread.currentThread().getContextClassLoader();
    classLoader.addTargetPackageFilter(name -> SKIP_PACKAGES.stream().noneMatch(name::startsWith));
}
```

**Comment by cpw** [comment]
MixinBootstrap is not something we care about. Mixin is natively supported through the ILaunchHandlerService. Something that sponge should provide as well.
