### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jamierocks** [cpw/modlauncher#5]
Currently, modlauncher has no license - much like LaunchWrapper. This is something that will concern a number of people - including myself who may well be using this in the future as a LaunchWrapper replacement. This may also be a blocker for potential contributors.

[As I am sure you are aware](https://github.com/MinecraftForge/MinecraftForge/issues/2789) relicensing after the fact can prove to be a [rather long](https://github.com/SpongePowered/SpongeDocs/pull/573), tedious procedure. My point is, with only one contributor (other than yourself), you are in a perfect position to be picking a license.

I would like to see modlauncher have a permissive license such as MIT or BSD 3-Clause - however, I'm sure you'll pick a suitable license.

**Comment by cpw** [comment]
Hi @jamierocks yeah, licensing will be a big challenge for this project. It has many requirements to fulfill. I will be figuring this out before official release.
