### ISSUE TITLE
Discussion: Should Minecraft's own dependencies be added to the transform path by modlauncher

### ISSUE THREAD

**Issue by jediminer543** [cpw/modlauncher#56]
Ok, this has been changed to a discussion as I phrased it as if it were a bug (having seen people implying this was an already intended feature, and me assuming that minecraft's libraries would be registered along with it's own jar)

The discussion at hand is two fold:
- Are minecrafts libraries considered to be in the same class of special jars as the core code and as such should be added to the transformer path
- If not, this should be moved to FML to discuss as to whether FML should/shouldn't add them itself (as they aren't core code so should be handeld on a loader by loader basis)

Specifically, this asks should they be added to `classBytesFinder` here

**Comment by jediminer543** [comment]
My thoughts (and part of the reason for the original phrasing) would be the following:

The minecraft dependencies are as much a part of the core code as the minecraft code itself; minecraft cannot run without them, and were a modloader to wish to not provide them, it could reject them using `targetPackageFilter`

**Comment by Zidane** [comment]
To throw in my two cents after using ModLauncher for a while, I'd state this to be a FML issue.

ModLauncher can (and for the most part is) very much platform-agnostic. The few Minecraft references that exist could easily be refactored out but as it stands a 3rd party product (be it another modloader for this game or another game entirely) can easily use it as it stands.

Keeping in the spirit of that, I would throw this down to FML and do the small refactor here.

**Comment by cpw** [comment]
I agree with @Zidane here. I think it's not really ModLauncher's role to handle such distinctions.
