### ISSUE TITLE
This needs to get official before 1.13 releases

### ISSUE THREAD

**Issue by DerpyNerd** [cpw/modlauncher#6]
Hi there,
as 1.13 is very close now, we have to make this the official replacement for legacylauncher, or else other minecraft basemods like optifine will most likely continue using launchwrapper, which breaks compat with other basemods. So we should get Mojang to adopt this and write Transformation Services for their "old stuff" (so basically rewrite [these](https://github.com/Mojang/LegacyLauncher/tree/master/src/main/java/net/minecraft/launchwrapper/injector) for this system). Upside for Mojang: Compat with J9+ for their old versions. Upside for us: An established new class transformation framework for minecraft 1.13+

**Comment by cpw** [comment]
BTW: FML/Forge will be using this regardless. If Optifine and others wait, that's their issue. They won't work with Forge anymore.
