### ISSUE TITLE
Not compatible with Java 16

### ISSUE THREAD

**Issue by IzzelAliz** [cpw/modlauncher#65]
Due to [JEP 396](https://openjdk.java.net/jeps/396) you cannot access internal apis now.

There are 3 problems preventing modlauncher from running in JDK 16:

1. grossjava9hacks tries to access ucp field via reflection
2. SecureJarHandler has direct reference to sun api
3. SecureJarHandler tries to access jv field via reflection

**Comment by gigaherz** [comment]
FWIW, we are aware. We were discussing this last week. However it's good to have a tracking issue. 👍

**Comment by ZekerZhayard** [comment]
>sciwhiz12 (2021/3/25 11:04 UTC+8):
>  there's about three solutions that I know of for fixing the Java 16 problem:
>   \- remove all reflection. may be impossible in certain places
>   \- hack in --illegal-access=permit somehow to the command-line arguments
>   \- use the JDK-specific (non-spec) Add-Opens manifest attribute to force the relevant JDK modules open for reflection

After browsing [this message](https://discord.com/channels/313125603924639766/540691915373412393/822888691570573345) and [this message](https://discord.com/channels/313125603924639766/313125603924639766/824478781514973215) from @sciwhiz12 in Forge Discord, I have some additional content to add.

- The `Add-Opens` attribute has a limitation as described by [JEP 261](https://openjdk.java.net/jeps/261):
  >Each attribute can occur at most once, in the main section of a MANIFEST.MF file. A particular pair can be listed more than once. If a specified module was not resolved, or if a specified package does not exist, then the corresponding pair is ignored. These attributes are interpreted only in the main executable JAR file of an application, i.e., in the JAR file specified to the -jar option of the Java run-time launcher; they are ignored in all other JAR files.

  This means that this attribute can only take effect when `java -jar` is used, that is, it can only be effective in the server side. 
- There is an option called `-XX:+IgnoreUnrecognizedVMOptions` added by [JDK-6788376](https://bugs.openjdk.java.net/browse/JDK-6788376) that allows the JVM to ignore unknown options. 

Therefore, based on the above information, one of my personal solutions is: 
- Add the following content into the client profile version json:
  ```json
  {
      ...
      "arguments": {
          ...
          "jvm": [
              "-XX:+IgnoreUnrecognizedVMOptions",
              "--illegal-access=permit"
          ]
      },
      ...
  }
  ```
- Add the following content into the fmllauncher jar manifest:
  ```
  Add-Exports: java.base/sun.security.util
  Add-Opens: java.base/java.util.jar
  ```
- Apply https://github.com/cpw/grossjava9classpathhacks/pull/2

**Comment by LlamaLad7** [comment]
If using `Unsafe` wouldn't be an issue then this should work: https://github.com/Col-E/Recaf/pull/372/commits/65350906bac23e483ab9f619fed9d2b7f9fba348
